version: "3"

services:
  lens:
    image: kuanyong/kasmvnc-lens:latest
    environment:
      PUID: 1000
      PGID: 1000
    privileged: true # needed otherwise lens would not run
    # restart: always
    volumes:
      - /home/${USER}/.minikube:/home/${USER}/.minikube
      - /home/${USER}/.kube:/home/${USER}/.kube
      - /etc/ssl/certs/:/etc/ssl/certs/
      - /home/${USER}/.pki:/home/${USER}/.pki
      - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/
      - /etc/machine-id:/etc/machine-id
      - /home/${USER}/.config/Lens:/home/${USER}/.config/Lens
      - /home/${USER}/.config/gcloud:/home/${USER}/.config/gcloud
      - /home/${USER}/.config/aws:/home/${USER}/.config/aws
      - /etc/hostname:/etc/hostname
    shm_size: "1gb" #optional
    ports:
      - 9994:6901

  chrome:
    container_name: chrome
    image: kuanyong/kasmvnc-chrome:latest
    environment:
      PUID: 1000
      PGID: 1000
      FLAGS: "--no-default-browser-check --restore-last-session --wm-window-animations-disabled --disable-gpu"
      NO_PROXY: ${NO_PROXY}
    privileged: true
    restart: always
    volumes:
      - /etc/ssl/certs/:/etc/ssl/certs/
      - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/
      - /home/${USER}/.pki:/home/${USER}/.pki
      - /home/${USER}/Downloads:/home/${USER}/Downloads
      - /etc/machine-id:/etc/machine-id
      - /home/${USER}/.config/google-chrome:/home/${USER}/.config/google-chrome
      - /home/${USER}/.config/google:/home/${USER}/.config/google
      - /home/${USER}/.cache/google-chrome:/home/${USER}/.cache/google-chrome
      - /etc/hostname:/etc/hostname
    shm_size: "1gb" #optional
    ports:
      - 9992:6901
